services:
  vosk-server:
    image: alphacep/kaldi-en:latest
    restart: unless-stopped
    expose:
      - 2700
  esl-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FS_HOST=freeswitch
      - WS_ENDPOINT=ws://vosk-server:2700
    depends_on:
      - vosk-server
      - freeswitch
  freeswitch:
    build:
      context: ./freeswitch
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    expose:
      - 8021
    environment:
      - EXTENSION_PASSWORD=extensionpassword

